Actor Покупатель as cl
box Ваше приложение #lightgreen
Participant Ваше_приложение as app
Participant Ваш_сервер as appbe
end box
box RuStore #lightblue
Participant RuStore_Billing_Client as sdk
Participant RuStore_Сервер as be
end box
participant Приложение_для_оплаты as bank
cl -> app: Входит в ваше приложение
==Проверка доступности работы платежей==
activate app
app -> sdk: checkPurchasesAvailability
activate sdk
sdk -> app: Результат
deactivate app
deactivate sdk
==Покупка продукта==
app -> sdk: getProducts
activate app
activate sdk
sdk -> app: Список продуктов\nвашего приложения
deactivate sdk
app -> cl: Показ списка доступных покупок
cl -> app: Приобретение товара
app -> sdk: purchaseProduct
activate sdk
sdk -> cl: Запрос способа оплаты
cl -> sdk: Способ оплаты
sdk -> sdk: Проведение платежа
sdk -> app: Результат проведения платежа
deactivate sdk
deactivate app
group Опционально [Серверная валидация платежа]
app --> appbe: Информация о платеже
activate appbe
appbe --> be: Серверная валидация (public API)
activate be
be --> appbe: Достоверная информация о покупке
deactivate be
appbe --> appbe: Начисление товара покупателю
appbe --> app: Результат валидации
deactivate appbe
end
group#red Обязательно [Покупка потребляемого товара]
app -> sdk: confirmPurchase
activate sdk
sdk -> app: Результат потребления
deactivate sdk
end
group#red Обязательно [Обработка deeplink при оплате СБП, SberPay и тд]
app -> sdk: purchaseProduct
activate app
activate sdk
sdk -> cl: Запрос способа оплаты
cl -> sdk: Указал СБП\SberPay\TinkoffPay
sdk -> bank: Запуск процесса оплаты
activate bank
bank -> cl: Сценарий оплаты
cl -> bank: Оплата покупки
bank -> app: Возврат в приложение
deactivate bank
app -> sdk: onNewIntent
sdk -> app: Результат оплаты
deactivate app
sdk -> cl: Отображение платежной шторки с результатом оплаты
deactivate sdk
end


